//! Bulk operations for BulkJobItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateBulkJobItemDto;
use crate::application::service::BulkJobItemService;
use crate::domain::entity::BulkJobItem;

/// Bulk operation handler for BulkJobItem entities.
///
/// Wraps `BulkJobItemService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type BulkJobItemBulkService = GenericBulkService<BulkJobItem, CreateBulkJobItemDto, BulkJobItemService>;

// <<< CUSTOM
// END CUSTOM
