//! Bulk operations for BulkJob entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateBulkJobDto;
use crate::application::service::BulkJobService;
use crate::domain::entity::BulkJob;

/// Bulk operation handler for BulkJob entities.
///
/// Wraps `BulkJobService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type BulkJobBulkService = GenericBulkService<BulkJob, CreateBulkJobDto, BulkJobService>;

// <<< CUSTOM
// END CUSTOM
