//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod bulk_job_bulk;
pub mod bulk_job_item_bulk;

pub use bulk_job_bulk::BulkJobBulkService;
pub use bulk_job_item_bulk::BulkJobItemBulkService;

// <<< CUSTOM
// END CUSTOM
