//! BulkJobItem DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::BulkJobItem;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::BulkItemStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new BulkJobItem
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateBulkJobItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "job_id")]
    pub job_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "item_key")]
    pub item_key: String,
    pub status: BulkItemStatus,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub payload: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "applied_ref_type")]
    pub applied_ref_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "applied_ref_id")]
    pub applied_ref_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a BulkJobItem
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateBulkJobItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "job_id")]
    pub job_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "item_key")]
    pub item_key: String,
    pub status: BulkItemStatus,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub payload: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "applied_ref_type")]
    pub applied_ref_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "applied_ref_id")]
    pub applied_ref_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a BulkJobItem
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchBulkJobItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "job_id")]
    pub job_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_key")]
    pub item_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<BulkItemStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "applied_ref_type")]
    pub applied_ref_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "applied_ref_id")]
    pub applied_ref_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
}

impl PatchBulkJobItemDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.job_id.is_some() || self.company_id.is_some() || self.item_key.is_some() || self.status.is_some() || self.payload.is_some() || self.applied_ref_type.is_some() || self.applied_ref_id.is_some() || self.error_detail.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for BulkJobItem entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BulkJobItemResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub job_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub item_key: String,
    pub status: BulkItemStatus,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub payload: String,
    pub applied_ref_type: Option<String>,
    pub applied_ref_id: Option<Uuid>,
    pub error_detail: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for BulkJobItem entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BulkJobItemListResponseDto {
    /// List of items
    pub items: Vec<BulkJobItemResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl BulkJobItemListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<BulkJobItemResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BulkJobItemSummaryDto {
    pub id: Uuid,
    pub job_id: Uuid,
    pub company_id: Uuid,
    pub item_key: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<BulkJobItem> for BulkJobItemResponseDto {
    fn from(entity: BulkJobItem) -> Self {
        Self {
            id: entity.id,
            job_id: entity.job_id,
            company_id: entity.company_id,
            item_key: entity.item_key,
            status: entity.status,
            payload: entity.payload,
            applied_ref_type: entity.applied_ref_type,
            applied_ref_id: entity.applied_ref_id,
            error_detail: entity.error_detail,
            metadata: entity.metadata,
        }
    }
}

impl From<BulkJobItem> for BulkJobItemSummaryDto {
    fn from(entity: BulkJobItem) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            job_id: entity.job_id,
            company_id: entity.company_id,
            item_key: entity.item_key,
            created_at,
        }
    }
}

impl From<CreateBulkJobItemDto> for BulkJobItem {
    fn from(dto: CreateBulkJobItemDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            job_id: dto.job_id,
            company_id: dto.company_id,
            item_key: dto.item_key,
            status: dto.status,
            payload: dto.payload,
            applied_ref_type: dto.applied_ref_type,
            applied_ref_id: dto.applied_ref_id,
            error_detail: dto.error_detail,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&BulkJobItem> for BulkJobItemResponseDto {
    fn from(entity: &BulkJobItem) -> Self {
        Self {
            id: entity.id.clone(),
            job_id: entity.job_id.clone(),
            company_id: entity.company_id.clone(),
            item_key: entity.item_key.clone(),
            status: entity.status.clone(),
            payload: entity.payload.clone(),
            applied_ref_type: entity.applied_ref_type.clone(),
            applied_ref_id: entity.applied_ref_id.clone(),
            error_detail: entity.error_detail.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateBulkJobItemDto> for BulkJobItem {
    fn from_create_dto(dto: CreateBulkJobItemDto) -> backbone_core::ServiceResult<Self> {
        Ok(BulkJobItem::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateBulkJobItemDto> for BulkJobItem {
    fn apply_update(mut self, dto: UpdateBulkJobItemDto) -> backbone_core::ServiceResult<Self> {
        self.job_id = dto.job_id;
        self.company_id = dto.company_id;
        self.item_key = dto.item_key;
        self.status = dto.status;
        self.payload = dto.payload;
        self.applied_ref_type = dto.applied_ref_type;
        self.applied_ref_id = dto.applied_ref_id;
        self.error_detail = dto.error_detail;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to BulkJobItem here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

