//! BulkJob DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::BulkJob;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::BulkJobStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new BulkJob
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateBulkJobDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "operation_type")]
    pub operation_type: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "target_module")]
    pub target_module: String,
    pub status: BulkJobStatus,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "total_items")]
    pub total_items: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "succeeded_count")]
    pub succeeded_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "failed_count")]
    pub failed_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "submitted_by")]
    pub submitted_by: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a BulkJob
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateBulkJobDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "operation_type")]
    pub operation_type: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "target_module")]
    pub target_module: String,
    pub status: BulkJobStatus,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "total_items")]
    pub total_items: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "succeeded_count")]
    pub succeeded_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "failed_count")]
    pub failed_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "submitted_by")]
    pub submitted_by: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a BulkJob
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchBulkJobDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "operation_type")]
    pub operation_type: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "target_module")]
    pub target_module: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<BulkJobStatus>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "total_items")]
    pub total_items: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "succeeded_count")]
    pub succeeded_count: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "failed_count")]
    pub failed_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "submitted_by")]
    pub submitted_by: Option<Uuid>,
}

impl PatchBulkJobDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.operation_type.is_some() || self.target_module.is_some() || self.status.is_some() || self.total_items.is_some() || self.succeeded_count.is_some() || self.failed_count.is_some() || self.submitted_by.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for BulkJob entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BulkJobResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub operation_type: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub target_module: String,
    pub status: BulkJobStatus,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub total_items: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub succeeded_count: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub failed_count: i32,
    pub submitted_by: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for BulkJob entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BulkJobListResponseDto {
    /// List of items
    pub items: Vec<BulkJobResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl BulkJobListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<BulkJobResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct BulkJobSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub operation_type: String,
    pub target_module: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<BulkJob> for BulkJobResponseDto {
    fn from(entity: BulkJob) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            operation_type: entity.operation_type,
            target_module: entity.target_module,
            status: entity.status,
            total_items: entity.total_items,
            succeeded_count: entity.succeeded_count,
            failed_count: entity.failed_count,
            submitted_by: entity.submitted_by,
            metadata: entity.metadata,
        }
    }
}

impl From<BulkJob> for BulkJobSummaryDto {
    fn from(entity: BulkJob) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            operation_type: entity.operation_type,
            target_module: entity.target_module,
            created_at,
        }
    }
}

impl From<CreateBulkJobDto> for BulkJob {
    fn from(dto: CreateBulkJobDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            operation_type: dto.operation_type,
            target_module: dto.target_module,
            status: dto.status,
            total_items: dto.total_items,
            succeeded_count: dto.succeeded_count,
            failed_count: dto.failed_count,
            submitted_by: dto.submitted_by,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&BulkJob> for BulkJobResponseDto {
    fn from(entity: &BulkJob) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            operation_type: entity.operation_type.clone(),
            target_module: entity.target_module.clone(),
            status: entity.status.clone(),
            total_items: entity.total_items.clone(),
            succeeded_count: entity.succeeded_count.clone(),
            failed_count: entity.failed_count.clone(),
            submitted_by: entity.submitted_by.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateBulkJobDto> for BulkJob {
    fn from_create_dto(dto: CreateBulkJobDto) -> backbone_core::ServiceResult<Self> {
        Ok(BulkJob::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateBulkJobDto> for BulkJob {
    fn apply_update(mut self, dto: UpdateBulkJobDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.operation_type = dto.operation_type;
        self.target_module = dto.target_module;
        self.status = dto.status;
        self.total_items = dto.total_items;
        self.succeeded_count = dto.succeeded_count;
        self.failed_count = dto.failed_count;
        self.submitted_by = dto.submitted_by;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to BulkJob here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
