//! Domain policy for BulkJobItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::BulkJobItem;

/// Domain policy for BulkJobItem — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<BulkJobItem>` in the `// <<< CUSTOM` zone.
pub type BulkJobItemDomainPolicy = PermitAllPolicy<BulkJobItem>;

// <<< CUSTOM
// END CUSTOM
