//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod bulk_job_domain_policy;
pub mod bulk_job_item_domain_policy;

pub use bulk_job_domain_policy::BulkJobDomainPolicy;
pub use bulk_job_item_domain_policy::BulkJobItemDomainPolicy;

// <<< CUSTOM
// END CUSTOM
