//! Application service for BulkJob entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `bulk_job_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateBulkJobDto, UpdateBulkJobDto};
use crate::domain::entity::BulkJob;
use crate::infrastructure::persistence::BulkJobRepository;

/// Application service for BulkJob entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `bulk_job_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct BulkJobServiceCustom {
///     inner: Arc<BulkJobService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type BulkJobService = GenericCrudService<
    BulkJob,
    CreateBulkJobDto,
    UpdateBulkJobDto,
    BulkJobRepository,
>;

// <<< CUSTOM
// END CUSTOM
