-- BulkJobItem Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the bulkops.bulk_job_items table.
-- Customize this file to add your initial data.

-- INSERT INTO bulkops.bulk_job_items (
--     id,
--     job_id,
--     item_key,
--     status,
--     payload,
--     applied_ref_type,
--     applied_ref_id,
--     error_detail,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO bulkops.bulk_job_items (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

