-- BulkJob Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the bulkops.bulk_jobs table.
-- Customize this file to add your initial data.

-- INSERT INTO bulkops.bulk_jobs (
--     id,
--     company_id,
--     operation_type,
--     target_module,
--     status,
--     total_items,
--     succeeded_count,
--     failed_count,
--     submitted_by,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO bulkops.bulk_jobs (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

