-- Migration: Create bulk_jobs table
-- Generated by metaphor-schema

-- Create bulk_job_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bulk_job_status') THEN
        CREATE TYPE bulk_job_status AS ENUM ('pending', 'running', 'completed', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS bulkops;

CREATE TABLE IF NOT EXISTS bulkops.bulk_jobs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    operation_type TEXT NOT NULL,
    target_module TEXT NOT NULL,
    status bulk_job_status NOT NULL DEFAULT 'pending',
    total_items INTEGER NOT NULL DEFAULT 0,
    succeeded_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    submitted_by UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_bulk_jobs_company_id_status ON bulkops.bulk_jobs (company_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_bulk_jobs_metadata_gin ON bulkops.bulk_jobs USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_bulk_jobs_metadata_deleted_at ON bulkops.bulk_jobs ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_bulk_jobs_metadata_created_at ON bulkops.bulk_jobs ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_bulk_jobs_metadata_updated_at ON bulkops.bulk_jobs ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION bulkops.bulk_jobs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bulk_jobs_insert_audit ON bulkops.bulk_jobs;
CREATE TRIGGER bulk_jobs_insert_audit BEFORE INSERT ON bulkops.bulk_jobs
    FOR EACH ROW EXECUTE FUNCTION bulkops.bulk_jobs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bulk_jobs_update_audit ON bulkops.bulk_jobs;
CREATE TRIGGER bulk_jobs_update_audit BEFORE UPDATE ON bulkops.bulk_jobs
    FOR EACH ROW EXECUTE FUNCTION bulkops.bulk_jobs_audit_timestamp();
