-- Enum types for bulkops module
-- Generated by metaphor-schema

-- Create bulk_job_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bulk_job_status') THEN
        CREATE TYPE bulk_job_status AS ENUM ('pending', 'running', 'completed', 'failed');
    END IF;
END
$$;

-- Create bulk_item_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bulk_item_status') THEN
        CREATE TYPE bulk_item_status AS ENUM ('pending', 'applying', 'applied', 'failed');
    END IF;
END
$$;

