-- Migration: Create bulk_job_items table
-- Generated by metaphor-schema

-- Create bulk_item_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bulk_item_status') THEN
        CREATE TYPE bulk_item_status AS ENUM ('pending', 'applying', 'applied', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS bulkops;

CREATE TABLE IF NOT EXISTS bulkops.bulk_job_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    job_id UUID NOT NULL,
    item_key TEXT NOT NULL,
    status bulk_item_status NOT NULL DEFAULT 'pending',
    payload TEXT NOT NULL,
    applied_ref_type TEXT,
    applied_ref_id UUID,
    error_detail TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bulk_job_items_job_id_item_key ON bulkops.bulk_job_items (job_id, item_key);

CREATE INDEX IF NOT EXISTS idx_bulk_job_items_status ON bulkops.bulk_job_items (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_bulk_job_items_metadata_gin ON bulkops.bulk_job_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_bulk_job_items_metadata_deleted_at ON bulkops.bulk_job_items ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_bulk_job_items_metadata_created_at ON bulkops.bulk_job_items ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_bulk_job_items_metadata_updated_at ON bulkops.bulk_job_items ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION bulkops.bulk_job_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bulk_job_items_insert_audit ON bulkops.bulk_job_items;
CREATE TRIGGER bulk_job_items_insert_audit BEFORE INSERT ON bulkops.bulk_job_items
    FOR EACH ROW EXECUTE FUNCTION bulkops.bulk_job_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bulk_job_items_update_audit ON bulkops.bulk_job_items;
CREATE TRIGGER bulk_job_items_update_audit BEFORE UPDATE ON bulkops.bulk_job_items
    FOR EACH ROW EXECUTE FUNCTION bulkops.bulk_job_items_audit_timestamp();
