-- Company RLS fence for bulkops module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for bulkops.bulk_jobs
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE bulkops.bulk_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE bulkops.bulk_jobs FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bulk_jobs_company_isolation ON bulkops.bulk_jobs;
CREATE POLICY bulk_jobs_company_isolation ON bulkops.bulk_jobs
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

