-- Audit Triggers Migration for bulkops module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: BulkJob (bulkops.bulk_jobs)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION bulkops.bulk_jobs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bulk_jobs_insert_audit ON bulkops.bulk_jobs;
CREATE TRIGGER bulk_jobs_insert_audit BEFORE INSERT ON bulkops.bulk_jobs
    FOR EACH ROW EXECUTE FUNCTION bulkops.bulk_jobs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bulk_jobs_update_audit ON bulkops.bulk_jobs;
CREATE TRIGGER bulk_jobs_update_audit BEFORE UPDATE ON bulkops.bulk_jobs
    FOR EACH ROW EXECUTE FUNCTION bulkops.bulk_jobs_audit_timestamp();

-- ==============================================================================
-- Table: BulkJobItem (bulkops.bulk_job_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION bulkops.bulk_job_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bulk_job_items_insert_audit ON bulkops.bulk_job_items;
CREATE TRIGGER bulk_job_items_insert_audit BEFORE INSERT ON bulkops.bulk_job_items
    FOR EACH ROW EXECUTE FUNCTION bulkops.bulk_job_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bulk_job_items_update_audit ON bulkops.bulk_job_items;
CREATE TRIGGER bulk_job_items_update_audit BEFORE UPDATE ON bulkops.bulk_job_items
    FOR EACH ROW EXECUTE FUNCTION bulkops.bulk_job_items_audit_timestamp();

