//! Domain events for BulkJobItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BulkJobItem;

/// Domain events for BulkJobItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BulkJobItem>)` variant.
pub type BulkJobItemEvent = CrudEvent<BulkJobItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BulkJobItem events.
pub type BulkJobItemEventPublisher = Arc<dyn CrudEventPublisher<BulkJobItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBulkJobItemEventPublisher = NoOpCrudEventPublisher<BulkJobItem>;
