//! Event handler trait for BulkJobItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BulkJobItemEvent;

/// Event handler for BulkJobItem events.
/// Implement this trait to react to BulkJobItem lifecycle events.
pub trait BulkJobItemEventHandler: EventHandler<BulkJobItemEvent> {}
