//! Event handler trait for BulkJob events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::BulkJobEvent;

/// Event handler for BulkJob events.
/// Implement this trait to react to BulkJob lifecycle events.
pub trait BulkJobEventHandler: EventHandler<BulkJobEvent> {}
