//! Domain events for BulkJob entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::BulkJob;

/// Domain events for BulkJob — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<BulkJob>)` variant.
pub type BulkJobEvent = CrudEvent<BulkJob>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for BulkJob events.
pub type BulkJobEventPublisher = Arc<dyn CrudEventPublisher<BulkJob> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopBulkJobEventPublisher = NoOpCrudEventPublisher<BulkJob>;
