//! Event subscriber type aliases for Bulkops module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::BulkJobEvent;
use crate::domain::event::BulkJobItemEvent;

/// Subscriber for BulkJob events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BulkJobEventSubscriber = GenericEventSubscriber<BulkJobEvent>;

/// Subscriber for BulkJobItem events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type BulkJobItemEventSubscriber = GenericEventSubscriber<BulkJobItemEvent>;

// <<< CUSTOM
// END CUSTOM
