//! Repository trait for BulkJobItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BulkJobItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{BulkJobItem, BulkItemStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BulkJobItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BulkJobItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BulkJobItemPaginatedResult {
    pub data: Vec<BulkJobItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BulkJobItemFilter {
    pub job_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub item_key: Option<String>,
    pub status: Option<BulkItemStatus>,
    pub payload: Option<String>,
    pub applied_ref_type: Option<String>,
    pub applied_ref_id: Option<Uuid>,
    pub error_detail: Option<String>,
}

impl BulkJobItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.job_id.is_some() || self.company_id.is_some() || self.item_key.is_some() || self.status.is_some() || self.payload.is_some() || self.applied_ref_type.is_some() || self.applied_ref_id.is_some() || self.error_detail.is_some()
    }
}

/// Repository trait for BulkJobItem aggregate
///
/// This trait defines the persistence contract for BulkJobItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BulkJobItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new bulk_job_item entity
    async fn save(&self, entity: &BulkJobItem) -> Result<BulkJobItem>;

    /// Find bulk_job_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BulkJobItem>>;

    /// Find all bulk_job_item entities
    async fn find_all(&self) -> Result<Vec<BulkJobItem>>;

    /// Update bulk_job_item by ID
    async fn update(&self, id: &str, entity: &BulkJobItem) -> Result<Option<BulkJobItem>>;

    /// Delete bulk_job_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List bulk_job_item with pagination
    async fn list(&self, params: BulkJobItemPaginationParams) -> Result<BulkJobItemPaginatedResult>;

    /// List bulk_job_item with pagination and filters
    async fn list_with_filters(&self, params: BulkJobItemPaginationParams, filters: BulkJobItemFilter) -> Result<BulkJobItemPaginatedResult>;

    /// Count all bulk_job_item entities
    async fn count(&self) -> Result<u64>;

    /// Count bulk_job_item entities matching filters
    async fn count_with_filters(&self, filters: BulkJobItemFilter) -> Result<u64>;

    /// Check if bulk_job_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete bulk_job_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted bulk_job_item by ID
    async fn restore(&self, id: &str) -> Result<Option<BulkJobItem>>;

    /// List soft-deleted bulk_job_item entities
    async fn list_deleted(&self, params: BulkJobItemPaginationParams) -> Result<BulkJobItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save bulk_job_item entities
    async fn bulk_save(&self, entities: &[BulkJobItem]) -> Result<Vec<BulkJobItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
