//! Repository trait for BulkJob aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the BulkJob aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{BulkJob, BulkJobStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BulkJobPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl BulkJobPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct BulkJobPaginatedResult {
    pub data: Vec<BulkJob>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct BulkJobFilter {
    pub operation_type: Option<String>,
    pub target_module: Option<String>,
    pub status: Option<BulkJobStatus>,
    pub submitted_by: Option<Uuid>,
}

impl BulkJobFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.operation_type.is_some() || self.target_module.is_some() || self.status.is_some() || self.submitted_by.is_some()
    }
}

/// Repository trait for BulkJob aggregate
///
/// This trait defines the persistence contract for BulkJob entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait BulkJobRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new bulk_job entity
    async fn save(&self, entity: &BulkJob) -> Result<BulkJob>;

    /// Find bulk_job by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<BulkJob>>;

    /// Find all bulk_job entities
    async fn find_all(&self) -> Result<Vec<BulkJob>>;

    /// Update bulk_job by ID
    async fn update(&self, id: &str, entity: &BulkJob) -> Result<Option<BulkJob>>;

    /// Delete bulk_job by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List bulk_job with pagination
    async fn list(&self, params: BulkJobPaginationParams) -> Result<BulkJobPaginatedResult>;

    /// List bulk_job with pagination and filters
    async fn list_with_filters(&self, params: BulkJobPaginationParams, filters: BulkJobFilter) -> Result<BulkJobPaginatedResult>;

    /// Count all bulk_job entities
    async fn count(&self) -> Result<u64>;

    /// Count bulk_job entities matching filters
    async fn count_with_filters(&self, filters: BulkJobFilter) -> Result<u64>;

    /// Check if bulk_job exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete bulk_job by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted bulk_job by ID
    async fn restore(&self, id: &str) -> Result<Option<BulkJob>>;

    /// List soft-deleted bulk_job entities
    async fn list_deleted(&self, params: BulkJobPaginationParams) -> Result<BulkJobPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save bulk_job entities
    async fn bulk_save(&self, entities: &[BulkJob]) -> Result<Vec<BulkJob>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
