//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod bulk_job_repository;
pub mod bulk_job_item_repository;

// Re-exports
pub use bulk_job_repository::{
    BulkJobRepository,
    BulkJobPaginationParams,
    BulkJobPaginatedResult,
    BulkJobFilter,
};
pub use bulk_job_item_repository::{
    BulkJobItemRepository,
    BulkJobItemPaginationParams,
    BulkJobItemPaginatedResult,
    BulkJobItemFilter,
};
