//! Repository for BulkJob entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written BulkJob SQL — the job header insert and the pending/running/completed
//! roll-up (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BulkJob, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::org_scope;

use crate::domain::entity::BulkJob;

/// Table name for BulkJob entities
pub const TABLE_NAME: &str = "bulkops.bulk_jobs";

/// Repository for BulkJob entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BulkJobRepository(
    backbone_orm::GenericCrudRepository<BulkJob, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BulkJobRepository {
    type Target = backbone_orm::GenericCrudRepository<BulkJob, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BulkJobRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a job header insert writes.
///
/// Mirrors the raw column shape rather than the `BulkJob` entity: `status` is the literal `'pending'`
/// and the three counters start at 0 — none are parameters, exactly as the original write had them.
/// `total_items` is stamped afterwards by [`BulkJobRepository::set_total_items`], once the items that
/// actually survived the (job, item_key) dedup are known. Tenancy (ADR-0029): no scoping column —
/// a composing service's decorator stamps org ownership at composition time.
pub struct NewJobRow<'a> {
    pub id: Uuid,
    pub operation_type: &'a str,
    pub target_module: &'a str,
    pub submitted_by: Option<Uuid>,
}

/// What a run needs to know about its job before it drives the target port.
pub struct JobRunRow {
    pub operation_type: String,
}

/// Hand-written BulkJob SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl BulkJobRepository {
    /// Insert the job header.
    ///
    /// Takes the CALLER'S connection so the header and its items commit as ONE unit — a job must never
    /// exist without the items it claims. The caller has already relayed the ambient org scope onto it
    /// (`org_scope::bind_org_scope_on`) — don't re-bind here.
    pub async fn insert_job(
        &self,
        conn: &mut sqlx::PgConnection,
        j: &NewJobRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO bulkops.bulk_jobs
                 (id, operation_type, target_module, status, total_items, succeeded_count,
                  failed_count, submitted_by)
               VALUES ($1,$2,$3,'pending'::bulk_job_status,0,0,0,$4)"#,
        )
        .bind(j.id).bind(j.operation_type).bind(j.target_module).bind(j.submitted_by)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Stamp the job's item count once the batch's dedup outcome is known. Same caller-owned-tx contract
    /// as [`Self::insert_job`].
    pub async fn set_total_items(
        &self,
        conn: &mut sqlx::PgConnection,
        job_id: Uuid,
        total_items: i32,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE bulkops.bulk_jobs SET total_items=$2 WHERE id=$1")
            .bind(job_id).bind(total_items)
            .execute(conn)
            .await?;
        Ok(())
    }

    /// Read the operation a run applies under. `Ok(None)` = no such job in scope.
    ///
    /// ID-only: a run is identified by the job id alone. Tenancy (ADR-0029): the module owns no
    /// fence — this read rides the AMBIENT org scope via `org_scope::fetch_optional_row_scoped`
    /// (the request-dedicated connection a composing service scoped), so under a decorated
    /// deployment another tenant's job is simply not found. With no ambient scope the read runs
    /// plainly on the pool — the tenant-agnostic posture of an undecorated deployment.
    pub async fn fetch_for_run(
        &self,
        pool: &PgPool,
        job_id: Uuid,
    ) -> Result<Option<JobRunRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT operation_type FROM bulkops.bulk_jobs WHERE id=$1 AND (metadata->>'deleted_at') IS NULL")
                .bind(job_id),
        )
        .await?;
        Ok(row.map(|r| JobRunRow { operation_type: r.get("operation_type") }))
    }

    /// Mark the job running. ID-only, same scope contract as [`Self::fetch_for_run`].
    pub async fn mark_running(&self, pool: &PgPool, job_id: Uuid) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query("UPDATE bulkops.bulk_jobs SET status='running'::bulk_job_status WHERE id=$1")
                .bind(job_id),
        )
        .await?;
        Ok(())
    }

    /// Write the job's terminal status and counts, rolled up from the item ledger by the caller.
    /// `status` binds as `&str` with a DB-side `::bulk_job_status` cast, so a bad value fails as a DB
    /// error rather than a deserialize panic. ID-only, same scope contract as [`Self::fetch_for_run`].
    pub async fn set_outcome(
        &self,
        pool: &PgPool,
        job_id: Uuid,
        status: &str,
        succeeded_count: i32,
        failed_count: i32,
    ) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE bulkops.bulk_jobs
                   SET status=$2::bulk_job_status, succeeded_count=$3, failed_count=$4 WHERE id=$1"#,
            )
            .bind(job_id).bind(status).bind(succeeded_count).bind(failed_count),
        )
        .await
        .map(|_| ())
    }

    /// Read the job's stamped item count (for the completion event). ID-only, same scope contract as
    /// [`Self::fetch_for_run`].
    pub async fn fetch_total_items(&self, pool: &PgPool, job_id: Uuid) -> Result<i32, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query("SELECT total_items FROM bulkops.bulk_jobs WHERE id=$1").bind(job_id),
        )
        .await?;
        row.map(|r| r.get::<i32, _>("total_items"))
            .ok_or(sqlx::Error::RowNotFound)
    }
}

backbone_core::impl_crud_repository!(BulkJobRepository, BulkJob, soft_delete);
