//! Repository for BulkJob entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BulkJob, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::BulkJob;

/// Table name for BulkJob entities
pub const TABLE_NAME: &str = "bulkops.bulk_jobs";

/// Repository for BulkJob entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BulkJobRepository(
    backbone_orm::GenericCrudRepository<BulkJob, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BulkJobRepository {
    type Target = backbone_orm::GenericCrudRepository<BulkJob, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BulkJobRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(BulkJobRepository, BulkJob, soft_delete);
