//! Repository for BulkJobItem entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written BulkJobItem SQL — the (job, item_key) dedup insert, the CAS reserve that
//! makes each apply at-most-once, and the applied/failed outcome ledger (4-layer rule: services
//! orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BulkJobItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::BulkJobItem;

/// Table name for BulkJobItem entities
pub const TABLE_NAME: &str = "bulkops.bulk_job_items";

/// Repository for BulkJobItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BulkJobItemRepository(
    backbone_orm::GenericCrudRepository<BulkJobItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for BulkJobItemRepository {
    type Target = backbone_orm::GenericCrudRepository<BulkJobItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BulkJobItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an item insert writes.
///
/// Mirrors the raw column shape rather than the `BulkJobItem` entity: `status` is the literal
/// `'pending'`, and `payload` is the already-serialized JSON TEXT the column holds — the caller does the
/// `to_string()`, as the original write did.
pub struct NewItemRow<'a> {
    pub id: Uuid,
    pub job_id: Uuid,
    pub item_key: &'a str,
    pub payload: &'a str,
}

/// A pending item as loaded by a run. `payload` is the raw JSON TEXT off the column — the caller parses
/// it, so a malformed payload is the service's decision to make, not a repo panic.
pub struct PendingItemRow {
    pub id: Uuid,
    pub item_key: String,
    pub payload: String,
}

/// One failed item, as the failure report reads it. `payload` is raw JSON TEXT — see [`PendingItemRow`].
pub struct FailedItemRow {
    pub item_key: String,
    pub error_detail: Option<String>,
    pub payload: String,
}

/// The item ledger's authoritative outcome tally for a job — covers PRIOR runs too, which is why the job
/// counts are rolled up from here rather than from the current run's loop counters.
pub struct ItemCountsRow {
    pub applied: i64,
    pub failed: i64,
}

/// Hand-written BulkJobItem SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl BulkJobItemRepository {
    /// Insert one item, deduped on (job, item_key) — a duplicate key within the batch is collapsed.
    /// Returns the rows affected so the caller can count what actually landed.
    ///
    /// Takes the CALLER'S connection so the items and their job header commit as ONE unit. The caller has
    /// already bound the job's company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_item(
        &self,
        conn: &mut sqlx::PgConnection,
        it: &NewItemRow<'_>,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"INSERT INTO bulkops.bulk_job_items (id, job_id, item_key, status, payload)
               VALUES ($1,$2,$3,'pending'::bulk_item_status,$4)
               ON CONFLICT (job_id, item_key) DO NOTHING"#,
        )
        .bind(it.id).bind(it.job_id).bind(it.item_key).bind(it.payload)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Load the job's still-`pending` items — the run's work list. That predicate is what makes a re-run
    /// idempotent: an already-applied item is never picked up again.
    ///
    /// ID-only, fenced by the caller's connection scope — see [`Self::reserve`].
    pub async fn fetch_pending(
        &self,
        pool: &PgPool,
        job_id: Uuid,
    ) -> Result<Vec<PendingItemRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, item_key, payload FROM bulkops.bulk_job_items
                   WHERE job_id=$1 AND status='pending'::bulk_item_status"#,
            )
            .bind(job_id),
        )
        .await?;
        Ok(rows
            .iter()
            .map(|r| PendingItemRow {
                id: r.get("id"), item_key: r.get("item_key"), payload: r.get("payload"),
            })
            .collect())
    }

    /// RESERVE an item before the external apply — a CAS `pending → applying`. Returns the rows affected:
    /// exactly 1 means the caller owns this item and may call the target port; 0 means a concurrent runner
    /// owns it and the caller must skip.
    ///
    /// This CAS must stay BEFORE the apply. It protects the APPLY, not just the count — moving it after
    /// would let two concurrent runs both apply the same item (maturity council 2026-07-10).
    ///
    /// ID-only: no company argument. The update rides the connection carrying the caller's
    /// `app.company_id`, so another company's item is simply not matched. A non-request caller must wrap
    /// the whole run in `with_company_scope(Some(company_id))` — otherwise this fails closed and every
    /// item is skipped.
    pub async fn reserve(&self, pool: &PgPool, item_id: Uuid) -> Result<u64, sqlx::Error> {
        let done = company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE bulkops.bulk_job_items SET status='applying'::bulk_item_status
                   WHERE id=$1 AND status='pending'::bulk_item_status"#,
            )
            .bind(item_id),
        )
        .await?;
        Ok(done.rows_affected())
    }

    /// Record a successful apply, pointing at what the target write path created. State-guarded on
    /// `applying` — only the reserver can close its own item out. ID-only, same RLS contract as
    /// [`Self::reserve`].
    pub async fn mark_applied(
        &self,
        pool: &PgPool,
        item_id: Uuid,
        applied_ref_type: &str,
        applied_ref_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE bulkops.bulk_job_items
                   SET status='applied'::bulk_item_status, applied_ref_type=$2, applied_ref_id=$3
                   WHERE id=$1 AND status='applying'::bulk_item_status"#,
            )
            .bind(item_id).bind(applied_ref_type).bind(applied_ref_id),
        )
        .await?;
        Ok(())
    }

    /// Record a failed apply — the isolation step that lets the batch continue. State-guarded on
    /// `applying`; ID-only, same RLS contract as [`Self::reserve`].
    pub async fn mark_failed(
        &self,
        pool: &PgPool,
        item_id: Uuid,
        error_detail: &str,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE bulkops.bulk_job_items
                   SET status='failed'::bulk_item_status, error_detail=$2
                   WHERE id=$1 AND status='applying'::bulk_item_status"#,
            )
            .bind(item_id).bind(error_detail),
        )
        .await?;
        Ok(())
    }

    /// The job's authoritative applied/failed tally, counted DB-side across ALL runs. ID-only, same RLS
    /// contract as [`Self::reserve`].
    pub async fn count_outcomes(
        &self,
        pool: &PgPool,
        job_id: Uuid,
    ) -> Result<ItemCountsRow, sqlx::Error> {
        let r = company_scope::fetch_one_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT
                     count(*) FILTER (WHERE status='applied'::bulk_item_status) AS applied,
                     count(*) FILTER (WHERE status='failed'::bulk_item_status)  AS failed
                   FROM bulkops.bulk_job_items WHERE job_id=$1"#,
            )
            .bind(job_id),
        )
        .await?;
        Ok(ItemCountsRow { applied: r.get("applied"), failed: r.get("failed") })
    }

    /// The job's failed items with key, error, and payload — the operator's failure report. ID-only, same
    /// RLS contract as [`Self::reserve`], so another company's job reports no failures.
    pub async fn fetch_failed(
        &self,
        pool: &PgPool,
        job_id: Uuid,
    ) -> Result<Vec<FailedItemRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT item_key, error_detail, payload FROM bulkops.bulk_job_items
                   WHERE job_id=$1 AND status='failed'::bulk_item_status
                   ORDER BY item_key"#,
            )
            .bind(job_id),
        )
        .await?;
        Ok(rows
            .iter()
            .map(|r| FailedItemRow {
                item_key: r.get("item_key"),
                error_detail: r.get("error_detail"),
                payload: r.get("payload"),
            })
            .collect())
    }

    /// Reset the job's FAILED items to `pending` so a re-run picks up just them, clearing the stale error.
    /// Returns the number requeued. ID-only, same RLS contract as [`Self::reserve`].
    pub async fn requeue_failed(&self, pool: &PgPool, job_id: Uuid) -> Result<u64, sqlx::Error> {
        let done = company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE bulkops.bulk_job_items
                   SET status='pending'::bulk_item_status, error_detail=NULL
                   WHERE job_id=$1 AND status='failed'::bulk_item_status"#,
            )
            .bind(job_id),
        )
        .await?;
        Ok(done.rows_affected())
    }
}

backbone_core::impl_crud_repository!(BulkJobItemRepository, BulkJobItem, soft_delete);
