//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod bulk_job_repository;
mod bulk_job_item_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use bulk_job_repository::BulkJobRepository;
pub use bulk_job_item_repository::BulkJobItemRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written bulkops SQL's parameter/projection types (see `bulk_job_repository` and
// `bulk_job_item_repository`, both declared `user_owned` in metaphor.codegen.yaml).
pub use bulk_job_item_repository::{FailedItemRow, ItemCountsRow, NewItemRow, PendingItemRow};
pub use bulk_job_repository::{JobRunRow, NewJobRow};
// END CUSTOM