//! Validator for BulkJob entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<BulkJob>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::BulkJob;

/// Validator type alias for BulkJob entities.
pub type BulkJobValidator = EntityValidator<BulkJob>;

/// Build a validator for BulkJob with all schema-defined field rules.
pub fn bulk_job_validator() -> BulkJobValidator {
    EntityValidator::new()
        .rule(RequiredString::new("operation_type", |e: &BulkJob| &e.operation_type))
        .rule(RequiredString::new("target_module", |e: &BulkJob| &e.target_module))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
