//! Validator for BulkJobItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<BulkJobItem>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::BulkJobItem;

/// Validator type alias for BulkJobItem entities.
pub type BulkJobItemValidator = EntityValidator<BulkJobItem>;

/// Build a validator for BulkJobItem with all schema-defined field rules.
pub fn bulk_job_item_validator() -> BulkJobItemValidator {
    EntityValidator::new()
        .rule(RequiredString::new("item_key", |e: &BulkJobItem| &e.item_key))
        .rule(RequiredString::new("payload", |e: &BulkJobItem| &e.payload))
        .rule(OptionalNotBlank::new("applied_ref_type", |e: &BulkJobItem| e.applied_ref_type.as_deref()))
        .rule(OptionalNotBlank::new("error_detail", |e: &BulkJobItem| e.error_detail.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
