//! Auth configuration for BulkJobItem handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<BulkJobItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BulkJobItemService;
use crate::domain::entity::BulkJobItem;

/// Permission string constants for BulkJobItem operations.
pub mod permissions {
    pub const LIST:        &str = "bulk_job_item:list";
    pub const READ:        &str = "bulk_job_item:read";
    pub const CREATE:      &str = "bulk_job_item:create";
    pub const UPDATE:      &str = "bulk_job_item:update";
    pub const DELETE:      &str = "bulk_job_item:delete";
    pub const RESTORE:     &str = "bulk_job_item:restore";
    pub const TRASH:       &str = "bulk_job_item:trash";
    pub const EMPTY_TRASH: &str = "bulk_job_item:empty_trash";
    pub const BULK_CREATE: &str = "bulk_job_item:bulk_create";
    pub const UPSERT:      &str = "bulk_job_item:upsert";
}

/// Resource policy for BulkJobItem — maps CRUD actions to permission strings.
pub struct BulkJobItemPolicy;

#[async_trait]
impl ResourcePolicy<BulkJobItem> for BulkJobItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &BulkJobItem,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for BulkJobItem handlers.
///
/// Wraps `BulkJobItemService` and checks `BulkJobItemPolicy` before delegating.
pub type BulkJobItemGuard = PermissionGuard<BulkJobItem>;

/// Service-integrated permission guard for BulkJobItem (for use in generated handlers).
pub type BulkJobItemServiceGuard = ServicePermissionGuard<BulkJobItem, BulkJobItemService, BulkJobItemPolicy>;

// <<< CUSTOM
// END CUSTOM
