//! Auth configuration for BulkJob handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<BulkJob>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BulkJobService;
use crate::domain::entity::BulkJob;

/// Permission string constants for BulkJob operations.
pub mod permissions {
    pub const LIST:        &str = "bulk_job:list";
    pub const READ:        &str = "bulk_job:read";
    pub const CREATE:      &str = "bulk_job:create";
    pub const UPDATE:      &str = "bulk_job:update";
    pub const DELETE:      &str = "bulk_job:delete";
    pub const RESTORE:     &str = "bulk_job:restore";
    pub const TRASH:       &str = "bulk_job:trash";
    pub const EMPTY_TRASH: &str = "bulk_job:empty_trash";
    pub const BULK_CREATE: &str = "bulk_job:bulk_create";
    pub const UPSERT:      &str = "bulk_job:upsert";
}

/// Resource policy for BulkJob — maps CRUD actions to permission strings.
pub struct BulkJobPolicy;

#[async_trait]
impl ResourcePolicy<BulkJob> for BulkJobPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &BulkJob,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for BulkJob handlers.
///
/// Wraps `BulkJobService` and checks `BulkJobPolicy` before delegating.
pub type BulkJobGuard = PermissionGuard<BulkJob>;

/// Service-integrated permission guard for BulkJob (for use in generated handlers).
pub type BulkJobServiceGuard = ServicePermissionGuard<BulkJob, BulkJobService, BulkJobPolicy>;

// <<< CUSTOM
// END CUSTOM
