//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod bulk_job_auth;
pub mod bulk_job_item_auth;

pub use bulk_job_auth::{BulkJobPolicy, BulkJobGuard, BulkJobServiceGuard};
pub use bulk_job_item_auth::{BulkJobItemPolicy, BulkJobItemGuard, BulkJobItemServiceGuard};

// <<< CUSTOM
// END CUSTOM
