//! BulkJobItem API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the BulkJobItem CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// BULKJOBITEM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for BulkJobItem
pub struct BulkJobItemTestData;

impl TestDataGenerator for BulkJobItemTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "job_id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "item_key": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "pending",
            "payload": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "applied_ref_type": null,
            "applied_ref_id": null,
            "error_detail": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "job_id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "item_key": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "pending",
            "payload": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "applied_ref_type": null,
            "applied_ref_id": null,
            "error_detail": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/bulk_jobs", &super::bulk_job_api_test::BulkJobTestData).await {
            deps.push(("job_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// BULKJOBITEM API TEST
// ============================================================================

/// BulkJobItem API test suite
pub struct BulkJobItemApiTest {
    inner: GenericCrudTest<BulkJobItemTestData>,
}

impl BulkJobItemApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/bulk_job_items", "BulkJobItem");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, BulkJobItemTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for BulkJobItemApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_bulk_job_item_crud() {
        let mut test = BulkJobItemApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add BulkJobItem specific tests here
// <<< CUSTOM TESTS END >>>
