//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod bulk_job_api_test;
pub mod bulk_job_item_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use bulk_job_api_test::*;
pub use bulk_job_item_api_test::*;
