//! Bulkops Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::BulkJobService;
use crate::application::service::BulkJobItemService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// BulkJob service
    pub bulk_job_service: Arc<BulkJobService>,
    /// BulkJobItem service
    pub bulk_job_item_service: Arc<BulkJobItemService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        bulk_job_service: Arc<BulkJobService>,
        bulk_job_item_service: Arc<BulkJobItemService>
    ) -> Self {
        Self {
            bulk_job_service,
            bulk_job_item_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::BulkopsModule) -> Self {
        Self {
            bulk_job_service: module.bulk_job_service.clone(),
            bulk_job_item_service: module.bulk_job_item_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    bulk_job_service: Option<Arc<BulkJobService>>,
    bulk_job_item_service: Option<Arc<BulkJobItemService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the BulkJob service.
    pub fn with_bulk_job_service(mut self, service: Arc<BulkJobService>) -> Self {
        self.bulk_job_service = Some(service);
        self
    }

    /// Set the BulkJobItem service.
    pub fn with_bulk_job_item_service(mut self, service: Arc<BulkJobItemService>) -> Self {
        self.bulk_job_item_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            bulk_job_service: self.bulk_job_service.expect("bulk_job_service is required"),
            bulk_job_item_service: self.bulk_job_item_service.expect("bulk_job_item_service is required"),
        }
    }
}
