//! Public events for Bulkops module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// BULKJOB EVENTS
// ============================================================================

/// Event published when a BulkJob is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobCreatedEvent {
    pub id: BulkJobId,
    pub data: BulkJobDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a BulkJob is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobUpdatedEvent {
    pub id: BulkJobId,
    pub data: BulkJobDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a BulkJob is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobDeletedEvent {
    pub id: BulkJobId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// BULKJOBITEM EVENTS
// ============================================================================

/// Event published when a BulkJobItem is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobItemCreatedEvent {
    pub id: BulkJobItemId,
    pub data: BulkJobItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a BulkJobItem is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobItemUpdatedEvent {
    pub id: BulkJobItemId,
    pub data: BulkJobItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a BulkJobItem is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobItemDeletedEvent {
    pub id: BulkJobItemId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Bulkops module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum BulkopsEvent {
    BulkJobCreated(BulkJobCreatedEvent),
    BulkJobUpdated(BulkJobUpdatedEvent),
    BulkJobDeleted(BulkJobDeletedEvent),
    BulkJobItemCreated(BulkJobItemCreatedEvent),
    BulkJobItemUpdated(BulkJobItemUpdatedEvent),
    BulkJobItemDeleted(BulkJobItemDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkopsEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for BulkopsEventMetadata {
    fn default() -> Self {
        Self {
            module: "bulkops",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
