//! Bulkops Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Bulkops exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use bulkops::exports::{BulkJobDto, BulkopsQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `BulkJobDto` - Data transfer object for BulkJob
/// - `BulkJobSummary` - Summary view of BulkJob
/// - `BulkJobId` - Type-safe ID wrapper
/// - `BulkJobItemDto` - Data transfer object for BulkJobItem
/// - `BulkJobItemSummary` - Summary view of BulkJobItem
/// - `BulkJobItemId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `BulkopsQueryService` - Read-only queries
///
/// ## Public Events
/// - `BulkJobCreatedEvent` - Published when BulkJob is created
/// - `BulkJobUpdatedEvent` - Published when BulkJob is updated
/// - `BulkJobDeletedEvent` - Published when BulkJob is deleted
/// - `BulkJobItemCreatedEvent` - Published when BulkJobItem is created
/// - `BulkJobItemUpdatedEvent` - Published when BulkJobItem is updated
/// - `BulkJobItemDeletedEvent` - Published when BulkJobItem is deleted
pub struct ExportSummary;
