//! Public services for Bulkops module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Bulkops module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait BulkopsQueryService: Send + Sync {
    /// Get BulkJob by ID
    async fn get_bulk_job(&self, id: BulkJobId) -> Result<Option<BulkJobDto>>;

    /// Get BulkJob summary by ID
    async fn get_bulk_job_summary(&self, id: BulkJobId) -> Result<Option<BulkJobSummary>>;

    /// Check if BulkJob exists
    async fn bulk_job_exists(&self, id: BulkJobId) -> Result<bool>;

    /// Get BulkJobItem by ID
    async fn get_bulk_job_item(&self, id: BulkJobItemId) -> Result<Option<BulkJobItemDto>>;

    /// Get BulkJobItem summary by ID
    async fn get_bulk_job_item_summary(&self, id: BulkJobItemId) -> Result<Option<BulkJobItemSummary>>;

    /// Check if BulkJobItem exists
    async fn bulk_job_item_exists(&self, id: BulkJobItemId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of BulkopsQueryService
pub struct BulkopsQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> BulkopsQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
