//! Public types for Bulkops module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// BULKJOB TYPES
// ============================================================================

/// Type-safe ID for BulkJob
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BulkJobId(pub Uuid);

impl BulkJobId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for BulkJobId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<BulkJobId> for Uuid {
    fn from(id: BulkJobId) -> Self {
        id.0
    }
}

/// Data transfer object for BulkJob
///
/// This is the public representation of BulkJob for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobDto {
    pub id: BulkJobId,
    pub company_id: Uuid,
    pub operation_type: String,
    pub target_module: String,
    pub status: BulkJobStatus,
    pub total_items: i32,
    pub succeeded_count: i32,
    pub failed_count: i32,
    pub submitted_by: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of BulkJob for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobSummary {
    pub id: BulkJobId,
    pub status: BulkJobStatus,
}

/// Reference to BulkJob for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobRef {
    pub id: BulkJobId,
}

// ============================================================================
// BULKJOBITEM TYPES
// ============================================================================

/// Type-safe ID for BulkJobItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BulkJobItemId(pub Uuid);

impl BulkJobItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for BulkJobItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<BulkJobItemId> for Uuid {
    fn from(id: BulkJobItemId) -> Self {
        id.0
    }
}

/// Data transfer object for BulkJobItem
///
/// This is the public representation of BulkJobItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobItemDto {
    pub id: BulkJobItemId,
    pub job_id: Uuid,
    pub company_id: Uuid,
    pub item_key: String,
    pub status: BulkItemStatus,
    pub payload: String,
    pub applied_ref_type: Option<String>,
    pub applied_ref_id: Option<Uuid>,
    pub error_detail: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of BulkJobItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobItemSummary {
    pub id: BulkJobItemId,
    pub status: BulkItemStatus,
}

/// Reference to BulkJobItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkJobItemRef {
    pub id: BulkJobItemId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
