//! Bulkops Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::BulkJobService;
pub use application::service::BulkJobItemService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Bulkops module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let bulkops = BulkopsModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = bulkops.all_crud_routes();
/// ```
pub struct BulkopsModule {
    pub bulk_job_service: Arc<BulkJobService>,
    pub bulk_job_item_service: Arc<BulkJobItemService>,
}

impl BulkopsModule {
    /// Create a new module builder
    pub fn builder() -> BulkopsModuleBuilder {
        BulkopsModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_bulk_job_routes,
            create_bulk_job_item_routes,
        };

        Router::new()
            .merge(create_bulk_job_routes(self.bulk_job_service.clone()))
            .merge(create_bulk_job_item_routes(self.bulk_job_item_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for BulkopsModule
pub struct BulkopsModuleBuilder {
    db_pool: Option<PgPool>,
}

impl BulkopsModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<BulkopsModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // BulkJob service
        let bulk_job_repository = Arc::new(BulkJobRepository::new(db_pool.clone()));
        let bulk_job_service = Arc::new(BulkJobService::with_repository(bulk_job_repository.clone()));

        // BulkJobItem service
        let bulk_job_item_repository = Arc::new(BulkJobItemRepository::new(db_pool.clone()));
        let bulk_job_item_service = Arc::new(BulkJobItemService::with_repository(bulk_job_item_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(BulkopsModule {
            bulk_job_service,
            bulk_job_item_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for BulkopsModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
