//! Use case type aliases for BulkJob aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBulkJobDto, UpdateBulkJobDto};
use crate::application::service::BulkJobService;
use crate::domain::entity::BulkJob;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBulkJobUseCase = CreateUseCase<BulkJob, CreateBulkJobDto, BulkJobService>;
pub type UpdateBulkJobUseCase = UpdateUseCase<BulkJob, UpdateBulkJobDto, BulkJobService>;
pub type GetBulkJobUseCase    = GetUseCase<BulkJob, BulkJobService>;
pub type DeleteBulkJobUseCase = DeleteUseCase<BulkJob, BulkJobService>;
pub type ListBulkJobUseCase   = ListUseCase<BulkJob, BulkJobService>;

// <<< CUSTOM
// END CUSTOM
