//! Use case type aliases for BulkJobItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateBulkJobItemDto, UpdateBulkJobItemDto};
use crate::application::service::BulkJobItemService;
use crate::domain::entity::BulkJobItem;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateBulkJobItemUseCase = CreateUseCase<BulkJobItem, CreateBulkJobItemDto, BulkJobItemService>;
pub type UpdateBulkJobItemUseCase = UpdateUseCase<BulkJobItem, UpdateBulkJobItemDto, BulkJobItemService>;
pub type GetBulkJobItemUseCase    = GetUseCase<BulkJobItem, BulkJobItemService>;
pub type DeleteBulkJobItemUseCase = DeleteUseCase<BulkJobItem, BulkJobItemService>;
pub type ListBulkJobItemUseCase   = ListUseCase<BulkJobItem, BulkJobItemService>;

// <<< CUSTOM
// END CUSTOM
