//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod bulk_job_usecases;
pub mod bulk_job_item_usecases;

pub use bulk_job_usecases::{
    CreateBulkJobUseCase, UpdateBulkJobUseCase, GetBulkJobUseCase,
    DeleteBulkJobUseCase, ListBulkJobUseCase,
};
pub use bulk_job_item_usecases::{
    CreateBulkJobItemUseCase, UpdateBulkJobItemUseCase, GetBulkJobItemUseCase,
    DeleteBulkJobItemUseCase, ListBulkJobItemUseCase,
};

// <<< CUSTOM
// END CUSTOM
